[package]
name = "vietlang"
version = "0.1.1"
edition = "2021"
description = "VietLang - A backend-first programming language"
authors = ["VanTrong"]

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
mysql = { version = "25.0", default-features = false }

[[bin]]
name = "vietlang"
path = "src/main.rs"
